#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pmdk
Version  : 1.4.2
Release  : 9
URL      : https://github.com/pmem/pmdk/archive/1.4.2.tar.gz
Source0  : https://github.com/pmem/pmdk/archive/1.4.2.tar.gz
Summary  : libvmmalloc library from PMDK project
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: pmdk-bin
Requires: pmdk-lib
Requires: pmdk-data
Requires: pmdk-license
Requires: pmdk-man
BuildRequires : doxygen

%description
Persistent Memory Development Kit
The scripts found here are used during library development.

%package bin
Summary: bin components for the pmdk package.
Group: Binaries
Requires: pmdk-data
Requires: pmdk-license
Requires: pmdk-man

%description bin
bin components for the pmdk package.


%package data
Summary: data components for the pmdk package.
Group: Data

%description data
data components for the pmdk package.


%package dev
Summary: dev components for the pmdk package.
Group: Development
Requires: pmdk-lib
Requires: pmdk-bin
Requires: pmdk-data
Provides: pmdk-devel

%description dev
dev components for the pmdk package.


%package doc
Summary: doc components for the pmdk package.
Group: Documentation
Requires: pmdk-man

%description doc
doc components for the pmdk package.


%package lib
Summary: lib components for the pmdk package.
Group: Libraries
Requires: pmdk-data
Requires: pmdk-license

%description lib
lib components for the pmdk package.


%package license
Summary: license components for the pmdk package.
Group: Default

%description license
license components for the pmdk package.


%package man
Summary: man components for the pmdk package.
Group: Default

%description man
man components for the pmdk package.


%prep
%setup -q -n pmdk-1.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534481473
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1534481473
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pmdk
cp LICENSE %{buildroot}/usr/share/doc/pmdk/LICENSE
cp src/jemalloc/COPYING %{buildroot}/usr/share/doc/pmdk/src_jemalloc_COPYING
cp src/windows/getopt/LICENSE.txt %{buildroot}/usr/share/doc/pmdk/src_windows_getopt_LICENSE.txt
cp src/windows/setup/license.rtf %{buildroot}/usr/share/doc/pmdk/src_windows_setup_license.rtf
%make_install prefix=/usr bashcompdir=/usr/share/bash-completion/completions

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pmempool

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/pmempool

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/libpmemobj++/allocator.hpp
/usr/include/libpmemobj++/condition_variable.hpp
/usr/include/libpmemobj++/detail/array_traits.hpp
/usr/include/libpmemobj++/detail/check_persistent_ptr_array.hpp
/usr/include/libpmemobj++/detail/common.hpp
/usr/include/libpmemobj++/detail/conversions.hpp
/usr/include/libpmemobj++/detail/integer_sequence.hpp
/usr/include/libpmemobj++/detail/life.hpp
/usr/include/libpmemobj++/detail/make_atomic_impl.hpp
/usr/include/libpmemobj++/detail/persistent_ptr_base.hpp
/usr/include/libpmemobj++/detail/pexceptions.hpp
/usr/include/libpmemobj++/detail/specialization.hpp
/usr/include/libpmemobj++/make_persistent.hpp
/usr/include/libpmemobj++/make_persistent_array.hpp
/usr/include/libpmemobj++/make_persistent_array_atomic.hpp
/usr/include/libpmemobj++/make_persistent_atomic.hpp
/usr/include/libpmemobj++/mutex.hpp
/usr/include/libpmemobj++/p.hpp
/usr/include/libpmemobj++/persistent_ptr.hpp
/usr/include/libpmemobj++/pext.hpp
/usr/include/libpmemobj++/pool.hpp
/usr/include/libpmemobj++/shared_mutex.hpp
/usr/include/libpmemobj++/timed_mutex.hpp
/usr/include/libpmemobj++/transaction.hpp
/usr/include/libpmemobj++/utils.hpp
/usr/include/libpmemobj/action.h
/usr/include/libpmemobj/action_base.h
/usr/include/libpmemobj/atomic.h
/usr/include/libpmemobj/atomic_base.h
/usr/include/libpmemobj/base.h
/usr/include/libpmemobj/ctl.h
/usr/include/libpmemobj/iterator.h
/usr/include/libpmemobj/iterator_base.h
/usr/include/libpmemobj/lists_atomic.h
/usr/include/libpmemobj/lists_atomic_base.h
/usr/include/libpmemobj/pool.h
/usr/include/libpmemobj/pool_base.h
/usr/include/libpmemobj/thread.h
/usr/include/libpmemobj/tx.h
/usr/include/libpmemobj/tx_base.h
/usr/include/libpmemobj/types.h
/usr/lib64/libpmem.so
/usr/lib64/libpmemblk.so
/usr/lib64/libpmemcto.so
/usr/lib64/libpmemlog.so
/usr/lib64/libpmemobj.so
/usr/lib64/libpmempool.so
/usr/lib64/libvmem.so
/usr/lib64/libvmmalloc.so
/usr/lib64/pkgconfig/libpmem.pc
/usr/lib64/pkgconfig/libpmemblk.pc
/usr/lib64/pkgconfig/libpmemcto.pc
/usr/lib64/pkgconfig/libpmemlog.pc
/usr/lib64/pkgconfig/libpmemobj++.pc
/usr/lib64/pkgconfig/libpmemobj.pc
/usr/lib64/pkgconfig/libpmempool.pc
/usr/lib64/pkgconfig/libvmem.pc
/usr/lib64/pkgconfig/libvmmalloc.pc
/usr/share/man/man3/d_ro.3.gz
/usr/share/man/man3/d_rw.3.gz
/usr/share/man/man3/direct_ro.3.gz
/usr/share/man/man3/direct_rw.3.gz
/usr/share/man/man3/oid_equals.3.gz
/usr/share/man/man3/oid_instanceof.3.gz
/usr/share/man/man3/oid_is_null.3.gz
/usr/share/man/man3/pmem_check_version.3.gz
/usr/share/man/man3/pmem_deep_drain.3.gz
/usr/share/man/man3/pmem_deep_flush.3.gz
/usr/share/man/man3/pmem_deep_persist.3.gz
/usr/share/man/man3/pmem_drain.3.gz
/usr/share/man/man3/pmem_errormsg.3.gz
/usr/share/man/man3/pmem_flush.3.gz
/usr/share/man/man3/pmem_has_auto_flush.3.gz
/usr/share/man/man3/pmem_has_hw_drain.3.gz
/usr/share/man/man3/pmem_is_pmem.3.gz
/usr/share/man/man3/pmem_map_file.3.gz
/usr/share/man/man3/pmem_memcpy_nodrain.3.gz
/usr/share/man/man3/pmem_memcpy_persist.3.gz
/usr/share/man/man3/pmem_memmove_nodrain.3.gz
/usr/share/man/man3/pmem_memmove_persist.3.gz
/usr/share/man/man3/pmem_memset_nodrain.3.gz
/usr/share/man/man3/pmem_memset_persist.3.gz
/usr/share/man/man3/pmem_msync.3.gz
/usr/share/man/man3/pmem_persist.3.gz
/usr/share/man/man3/pmem_unmap.3.gz
/usr/share/man/man3/pmemblk_bsize.3.gz
/usr/share/man/man3/pmemblk_check.3.gz
/usr/share/man/man3/pmemblk_check_version.3.gz
/usr/share/man/man3/pmemblk_close.3.gz
/usr/share/man/man3/pmemblk_create.3.gz
/usr/share/man/man3/pmemblk_errormsg.3.gz
/usr/share/man/man3/pmemblk_nblock.3.gz
/usr/share/man/man3/pmemblk_open.3.gz
/usr/share/man/man3/pmemblk_read.3.gz
/usr/share/man/man3/pmemblk_set_error.3.gz
/usr/share/man/man3/pmemblk_set_funcs.3.gz
/usr/share/man/man3/pmemblk_set_zero.3.gz
/usr/share/man/man3/pmemblk_write.3.gz
/usr/share/man/man3/pmemcto_aligned_alloc.3.gz
/usr/share/man/man3/pmemcto_calloc.3.gz
/usr/share/man/man3/pmemcto_check.3.gz
/usr/share/man/man3/pmemcto_check_version.3.gz
/usr/share/man/man3/pmemcto_close.3.gz
/usr/share/man/man3/pmemcto_create.3.gz
/usr/share/man/man3/pmemcto_errormsg.3.gz
/usr/share/man/man3/pmemcto_free.3.gz
/usr/share/man/man3/pmemcto_get_root_pointer.3.gz
/usr/share/man/man3/pmemcto_malloc.3.gz
/usr/share/man/man3/pmemcto_malloc_usable_size.3.gz
/usr/share/man/man3/pmemcto_open.3.gz
/usr/share/man/man3/pmemcto_realloc.3.gz
/usr/share/man/man3/pmemcto_set_funcs.3.gz
/usr/share/man/man3/pmemcto_set_root_pointer.3.gz
/usr/share/man/man3/pmemcto_stats_print.3.gz
/usr/share/man/man3/pmemcto_strdup.3.gz
/usr/share/man/man3/pmemcto_wcsdup.3.gz
/usr/share/man/man3/pmemlog_append.3.gz
/usr/share/man/man3/pmemlog_appendv.3.gz
/usr/share/man/man3/pmemlog_check.3.gz
/usr/share/man/man3/pmemlog_check_version.3.gz
/usr/share/man/man3/pmemlog_close.3.gz
/usr/share/man/man3/pmemlog_create.3.gz
/usr/share/man/man3/pmemlog_errormsg.3.gz
/usr/share/man/man3/pmemlog_nbyte.3.gz
/usr/share/man/man3/pmemlog_open.3.gz
/usr/share/man/man3/pmemlog_rewind.3.gz
/usr/share/man/man3/pmemlog_set_funcs.3.gz
/usr/share/man/man3/pmemlog_tell.3.gz
/usr/share/man/man3/pmemlog_walk.3.gz
/usr/share/man/man3/pmemobj_action.3.gz
/usr/share/man/man3/pmemobj_alloc.3.gz
/usr/share/man/man3/pmemobj_alloc_usable_size.3.gz
/usr/share/man/man3/pmemobj_cancel.3.gz
/usr/share/man/man3/pmemobj_check.3.gz
/usr/share/man/man3/pmemobj_check_version.3.gz
/usr/share/man/man3/pmemobj_close.3.gz
/usr/share/man/man3/pmemobj_cond_broadcast.3.gz
/usr/share/man/man3/pmemobj_cond_signal.3.gz
/usr/share/man/man3/pmemobj_cond_timedwait.3.gz
/usr/share/man/man3/pmemobj_cond_wait.3.gz
/usr/share/man/man3/pmemobj_cond_zero.3.gz
/usr/share/man/man3/pmemobj_create.3.gz
/usr/share/man/man3/pmemobj_ctl_exec.3.gz
/usr/share/man/man3/pmemobj_ctl_get.3.gz
/usr/share/man/man3/pmemobj_ctl_set.3.gz
/usr/share/man/man3/pmemobj_direct.3.gz
/usr/share/man/man3/pmemobj_drain.3.gz
/usr/share/man/man3/pmemobj_errormsg.3.gz
/usr/share/man/man3/pmemobj_first.3.gz
/usr/share/man/man3/pmemobj_flush.3.gz
/usr/share/man/man3/pmemobj_free.3.gz
/usr/share/man/man3/pmemobj_list_insert.3.gz
/usr/share/man/man3/pmemobj_list_insert_new.3.gz
/usr/share/man/man3/pmemobj_list_move.3.gz
/usr/share/man/man3/pmemobj_list_remove.3.gz
/usr/share/man/man3/pmemobj_memcpy_persist.3.gz
/usr/share/man/man3/pmemobj_memset_persist.3.gz
/usr/share/man/man3/pmemobj_mutex_lock.3.gz
/usr/share/man/man3/pmemobj_mutex_timedlock.3.gz
/usr/share/man/man3/pmemobj_mutex_trylock.3.gz
/usr/share/man/man3/pmemobj_mutex_unlock.3.gz
/usr/share/man/man3/pmemobj_mutex_zero.3.gz
/usr/share/man/man3/pmemobj_next.3.gz
/usr/share/man/man3/pmemobj_oid.3.gz
/usr/share/man/man3/pmemobj_open.3.gz
/usr/share/man/man3/pmemobj_persist.3.gz
/usr/share/man/man3/pmemobj_pool_by_oid.3.gz
/usr/share/man/man3/pmemobj_pool_by_ptr.3.gz
/usr/share/man/man3/pmemobj_publish.3.gz
/usr/share/man/man3/pmemobj_realloc.3.gz
/usr/share/man/man3/pmemobj_reserve.3.gz
/usr/share/man/man3/pmemobj_root.3.gz
/usr/share/man/man3/pmemobj_root_construct.3.gz
/usr/share/man/man3/pmemobj_root_size.3.gz
/usr/share/man/man3/pmemobj_rwlock_rdlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_timedrdlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_timedwrlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_tryrdlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_trywrlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_unlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_wrlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_zero.3.gz
/usr/share/man/man3/pmemobj_set_funcs.3.gz
/usr/share/man/man3/pmemobj_set_value.3.gz
/usr/share/man/man3/pmemobj_strdup.3.gz
/usr/share/man/man3/pmemobj_tx_abort.3.gz
/usr/share/man/man3/pmemobj_tx_add_range.3.gz
/usr/share/man/man3/pmemobj_tx_add_range_direct.3.gz
/usr/share/man/man3/pmemobj_tx_alloc.3.gz
/usr/share/man/man3/pmemobj_tx_begin.3.gz
/usr/share/man/man3/pmemobj_tx_commit.3.gz
/usr/share/man/man3/pmemobj_tx_end.3.gz
/usr/share/man/man3/pmemobj_tx_errno.3.gz
/usr/share/man/man3/pmemobj_tx_free.3.gz
/usr/share/man/man3/pmemobj_tx_lock.3.gz
/usr/share/man/man3/pmemobj_tx_process.3.gz
/usr/share/man/man3/pmemobj_tx_publish.3.gz
/usr/share/man/man3/pmemobj_tx_realloc.3.gz
/usr/share/man/man3/pmemobj_tx_stage.3.gz
/usr/share/man/man3/pmemobj_tx_strdup.3.gz
/usr/share/man/man3/pmemobj_tx_wcsdup.3.gz
/usr/share/man/man3/pmemobj_tx_xadd_range.3.gz
/usr/share/man/man3/pmemobj_tx_xadd_range_direct.3.gz
/usr/share/man/man3/pmemobj_tx_xalloc.3.gz
/usr/share/man/man3/pmemobj_tx_zalloc.3.gz
/usr/share/man/man3/pmemobj_tx_zrealloc.3.gz
/usr/share/man/man3/pmemobj_type_num.3.gz
/usr/share/man/man3/pmemobj_wcsdup.3.gz
/usr/share/man/man3/pmemobj_xalloc.3.gz
/usr/share/man/man3/pmemobj_xreserve.3.gz
/usr/share/man/man3/pmemobj_zalloc.3.gz
/usr/share/man/man3/pmemobj_zrealloc.3.gz
/usr/share/man/man3/pmempool_check.3.gz
/usr/share/man/man3/pmempool_check_end.3.gz
/usr/share/man/man3/pmempool_check_init.3.gz
/usr/share/man/man3/pmempool_check_version.3.gz
/usr/share/man/man3/pmempool_errormsg.3.gz
/usr/share/man/man3/pmempool_rm.3.gz
/usr/share/man/man3/pmempool_sync.3.gz
/usr/share/man/man3/pmempool_transform.3.gz
/usr/share/man/man3/pobj_alloc.3.gz
/usr/share/man/man3/pobj_first.3.gz
/usr/share/man/man3/pobj_first_type_num.3.gz
/usr/share/man/man3/pobj_foreach.3.gz
/usr/share/man/man3/pobj_foreach_safe.3.gz
/usr/share/man/man3/pobj_foreach_safe_type.3.gz
/usr/share/man/man3/pobj_foreach_type.3.gz
/usr/share/man/man3/pobj_free.3.gz
/usr/share/man/man3/pobj_layout_begin.3.gz
/usr/share/man/man3/pobj_layout_end.3.gz
/usr/share/man/man3/pobj_layout_name.3.gz
/usr/share/man/man3/pobj_layout_root.3.gz
/usr/share/man/man3/pobj_layout_toid.3.gz
/usr/share/man/man3/pobj_layout_types_num.3.gz
/usr/share/man/man3/pobj_list_empty.3.gz
/usr/share/man/man3/pobj_list_entry.3.gz
/usr/share/man/man3/pobj_list_first.3.gz
/usr/share/man/man3/pobj_list_foreach.3.gz
/usr/share/man/man3/pobj_list_foreach_reverse.3.gz
/usr/share/man/man3/pobj_list_head.3.gz
/usr/share/man/man3/pobj_list_insert_after.3.gz
/usr/share/man/man3/pobj_list_insert_before.3.gz
/usr/share/man/man3/pobj_list_insert_head.3.gz
/usr/share/man/man3/pobj_list_insert_new_after.3.gz
/usr/share/man/man3/pobj_list_insert_new_before.3.gz
/usr/share/man/man3/pobj_list_insert_new_head.3.gz
/usr/share/man/man3/pobj_list_insert_new_tail.3.gz
/usr/share/man/man3/pobj_list_insert_tail.3.gz
/usr/share/man/man3/pobj_list_last.3.gz
/usr/share/man/man3/pobj_list_move_element_after.3.gz
/usr/share/man/man3/pobj_list_move_element_before.3.gz
/usr/share/man/man3/pobj_list_move_element_head.3.gz
/usr/share/man/man3/pobj_list_move_element_tail.3.gz
/usr/share/man/man3/pobj_list_next.3.gz
/usr/share/man/man3/pobj_list_prev.3.gz
/usr/share/man/man3/pobj_list_remove.3.gz
/usr/share/man/man3/pobj_list_remove_free.3.gz
/usr/share/man/man3/pobj_new.3.gz
/usr/share/man/man3/pobj_next.3.gz
/usr/share/man/man3/pobj_next_type_num.3.gz
/usr/share/man/man3/pobj_realloc.3.gz
/usr/share/man/man3/pobj_reserve_alloc.3.gz
/usr/share/man/man3/pobj_reserve_new.3.gz
/usr/share/man/man3/pobj_root.3.gz
/usr/share/man/man3/pobj_zalloc.3.gz
/usr/share/man/man3/pobj_znew.3.gz
/usr/share/man/man3/pobj_zrealloc.3.gz
/usr/share/man/man3/toid.3.gz
/usr/share/man/man3/toid_assign.3.gz
/usr/share/man/man3/toid_declare.3.gz
/usr/share/man/man3/toid_declare_root.3.gz
/usr/share/man/man3/toid_equals.3.gz
/usr/share/man/man3/toid_is_null.3.gz
/usr/share/man/man3/toid_offsetof.3.gz
/usr/share/man/man3/toid_type_num.3.gz
/usr/share/man/man3/toid_type_num_of.3.gz
/usr/share/man/man3/toid_typeof.3.gz
/usr/share/man/man3/toid_valid.3.gz
/usr/share/man/man3/tx_add.3.gz
/usr/share/man/man3/tx_add_direct.3.gz
/usr/share/man/man3/tx_add_field.3.gz
/usr/share/man/man3/tx_add_field_direct.3.gz
/usr/share/man/man3/tx_alloc.3.gz
/usr/share/man/man3/tx_begin.3.gz
/usr/share/man/man3/tx_begin_cb.3.gz
/usr/share/man/man3/tx_begin_param.3.gz
/usr/share/man/man3/tx_end.3.gz
/usr/share/man/man3/tx_finally.3.gz
/usr/share/man/man3/tx_free.3.gz
/usr/share/man/man3/tx_memcpy.3.gz
/usr/share/man/man3/tx_memset.3.gz
/usr/share/man/man3/tx_new.3.gz
/usr/share/man/man3/tx_onabort.3.gz
/usr/share/man/man3/tx_oncommit.3.gz
/usr/share/man/man3/tx_realloc.3.gz
/usr/share/man/man3/tx_set.3.gz
/usr/share/man/man3/tx_set_direct.3.gz
/usr/share/man/man3/tx_strdup.3.gz
/usr/share/man/man3/tx_wcsdup.3.gz
/usr/share/man/man3/tx_xadd.3.gz
/usr/share/man/man3/tx_xadd_direct.3.gz
/usr/share/man/man3/tx_xadd_field.3.gz
/usr/share/man/man3/tx_xadd_field_direct.3.gz
/usr/share/man/man3/tx_xalloc.3.gz
/usr/share/man/man3/tx_zalloc.3.gz
/usr/share/man/man3/tx_znew.3.gz
/usr/share/man/man3/tx_zrealloc.3.gz
/usr/share/man/man3/vmem_aligned_alloc.3.gz
/usr/share/man/man3/vmem_calloc.3.gz
/usr/share/man/man3/vmem_check.3.gz
/usr/share/man/man3/vmem_check_version.3.gz
/usr/share/man/man3/vmem_create.3.gz
/usr/share/man/man3/vmem_create_in_region.3.gz
/usr/share/man/man3/vmem_delete.3.gz
/usr/share/man/man3/vmem_errormsg.3.gz
/usr/share/man/man3/vmem_free.3.gz
/usr/share/man/man3/vmem_malloc.3.gz
/usr/share/man/man3/vmem_malloc_usable_size.3.gz
/usr/share/man/man3/vmem_realloc.3.gz
/usr/share/man/man3/vmem_set_funcs.3.gz
/usr/share/man/man3/vmem_stats_print.3.gz
/usr/share/man/man3/vmem_strdup.3.gz
/usr/share/man/man3/vmem_wcsdup.3.gz

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libpmemobj++-dev/allocator_8hpp.html
/usr/share/doc/libpmemobj++-dev/allocator_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/annotated.html
/usr/share/doc/libpmemobj++-dev/array__traits_8hpp.html
/usr/share/doc/libpmemobj++-dev/array__traits_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/bc_s.png
/usr/share/doc/libpmemobj++-dev/bdwn.png
/usr/share/doc/libpmemobj++-dev/check__persistent__ptr__array_8hpp.html
/usr/share/doc/libpmemobj++-dev/check__persistent__ptr__array_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/classes.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1detail_1_1persistent__ptr__base-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1detail_1_1persistent__ptr__base.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1detail_1_1persistent__ptr__base.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1lock__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1manual__tx__abort.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1allocator-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1allocator.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1condition__variable-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1condition__variable.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1mutex-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1mutex.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1object__traits-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1object__traits.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1object__traits_3_01void_01_4-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1object__traits_3_01void_01_4.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1p-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1p.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1persistent__ptr-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1persistent__ptr.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1persistent__ptr.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool__base-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool__base.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool__base.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1shared__mutex-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1shared__mutex.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1standard__alloc__policy-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1standard__alloc__policy.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1standard__alloc__policy_3_01void_01_4-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1standard__alloc__policy_3_01void_01_4.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1timed__mutex-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1timed__mutex.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1automatic-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1automatic.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1automatic_1_1uncaught__exception__counter-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1automatic_1_1uncaught__exception__counter.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1manual-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1manual.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1pool__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__alloc__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__alloc__error.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__error.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__free__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__free__error.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__scope__error.html
/usr/share/doc/libpmemobj++-dev/closed.png
/usr/share/doc/libpmemobj++-dev/common_8hpp.html
/usr/share/doc/libpmemobj++-dev/common_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/condition__variable_8hpp.html
/usr/share/doc/libpmemobj++-dev/condition__variable_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/conversions_8hpp.html
/usr/share/doc/libpmemobj++-dev/conversions_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/dir_6d567830b6bf2043b91ed9ca58fd071b.html
/usr/share/doc/libpmemobj++-dev/dir_a5e25029ca08f6980ba72569627aee2e.html
/usr/share/doc/libpmemobj++-dev/dir_d02785570911eb5e8e8222e4294f2aca.html
/usr/share/doc/libpmemobj++-dev/dir_db6c799aa7f0821d4018f77d17a806da.html
/usr/share/doc/libpmemobj++-dev/dir_f268a27e2c10b47ed8a46f6760e6b97c.html
/usr/share/doc/libpmemobj++-dev/doc.png
/usr/share/doc/libpmemobj++-dev/doxygen.css
/usr/share/doc/libpmemobj++-dev/doxygen.png
/usr/share/doc/libpmemobj++-dev/dynsections.js
/usr/share/doc/libpmemobj++-dev/files.html
/usr/share/doc/libpmemobj++-dev/folderclosed.png
/usr/share/doc/libpmemobj++-dev/folderopen.png
/usr/share/doc/libpmemobj++-dev/functions.html
/usr/share/doc/libpmemobj++-dev/functions_0x7e.html
/usr/share/doc/libpmemobj++-dev/functions_b.html
/usr/share/doc/libpmemobj++-dev/functions_c.html
/usr/share/doc/libpmemobj++-dev/functions_d.html
/usr/share/doc/libpmemobj++-dev/functions_e.html
/usr/share/doc/libpmemobj++-dev/functions_f.html
/usr/share/doc/libpmemobj++-dev/functions_func.html
/usr/share/doc/libpmemobj++-dev/functions_g.html
/usr/share/doc/libpmemobj++-dev/functions_i.html
/usr/share/doc/libpmemobj++-dev/functions_l.html
/usr/share/doc/libpmemobj++-dev/functions_m.html
/usr/share/doc/libpmemobj++-dev/functions_n.html
/usr/share/doc/libpmemobj++-dev/functions_o.html
/usr/share/doc/libpmemobj++-dev/functions_p.html
/usr/share/doc/libpmemobj++-dev/functions_r.html
/usr/share/doc/libpmemobj++-dev/functions_s.html
/usr/share/doc/libpmemobj++-dev/functions_t.html
/usr/share/doc/libpmemobj++-dev/functions_type.html
/usr/share/doc/libpmemobj++-dev/functions_u.html
/usr/share/doc/libpmemobj++-dev/functions_v.html
/usr/share/doc/libpmemobj++-dev/functions_vars.html
/usr/share/doc/libpmemobj++-dev/functions_w.html
/usr/share/doc/libpmemobj++-dev/hierarchy.html
/usr/share/doc/libpmemobj++-dev/index.html
/usr/share/doc/libpmemobj++-dev/integer__sequence_8hpp.html
/usr/share/doc/libpmemobj++-dev/integer__sequence_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/jquery.js
/usr/share/doc/libpmemobj++-dev/life_8hpp.html
/usr/share/doc/libpmemobj++-dev/life_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__atomic__impl_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__atomic__impl_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__persistent_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__persistent_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__persistent__array_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__persistent__array_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__persistent__array__atomic_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__persistent__array__atomic_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__persistent__atomic_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__persistent__atomic_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/menu.js
/usr/share/doc/libpmemobj++-dev/menudata.js
/usr/share/doc/libpmemobj++-dev/mutex_8hpp.html
/usr/share/doc/libpmemobj++-dev/mutex_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/nav_f.png
/usr/share/doc/libpmemobj++-dev/nav_g.png
/usr/share/doc/libpmemobj++-dev/nav_h.png
/usr/share/doc/libpmemobj++-dev/open.png
/usr/share/doc/libpmemobj++-dev/p_8hpp.html
/usr/share/doc/libpmemobj++-dev/p_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/persistent__ptr_8hpp.html
/usr/share/doc/libpmemobj++-dev/persistent__ptr_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/persistent__ptr__base_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/pexceptions_8hpp.html
/usr/share/doc/libpmemobj++-dev/pexceptions_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/pext_8hpp.html
/usr/share/doc/libpmemobj++-dev/pext_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/pool_8hpp.html
/usr/share/doc/libpmemobj++-dev/pool_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/search/all_0.html
/usr/share/doc/libpmemobj++-dev/search/all_0.js
/usr/share/doc/libpmemobj++-dev/search/all_1.html
/usr/share/doc/libpmemobj++-dev/search/all_1.js
/usr/share/doc/libpmemobj++-dev/search/all_10.html
/usr/share/doc/libpmemobj++-dev/search/all_10.js
/usr/share/doc/libpmemobj++-dev/search/all_11.html
/usr/share/doc/libpmemobj++-dev/search/all_11.js
/usr/share/doc/libpmemobj++-dev/search/all_12.html
/usr/share/doc/libpmemobj++-dev/search/all_12.js
/usr/share/doc/libpmemobj++-dev/search/all_13.html
/usr/share/doc/libpmemobj++-dev/search/all_13.js
/usr/share/doc/libpmemobj++-dev/search/all_2.html
/usr/share/doc/libpmemobj++-dev/search/all_2.js
/usr/share/doc/libpmemobj++-dev/search/all_3.html
/usr/share/doc/libpmemobj++-dev/search/all_3.js
/usr/share/doc/libpmemobj++-dev/search/all_4.html
/usr/share/doc/libpmemobj++-dev/search/all_4.js
/usr/share/doc/libpmemobj++-dev/search/all_5.html
/usr/share/doc/libpmemobj++-dev/search/all_5.js
/usr/share/doc/libpmemobj++-dev/search/all_6.html
/usr/share/doc/libpmemobj++-dev/search/all_6.js
/usr/share/doc/libpmemobj++-dev/search/all_7.html
/usr/share/doc/libpmemobj++-dev/search/all_7.js
/usr/share/doc/libpmemobj++-dev/search/all_8.html
/usr/share/doc/libpmemobj++-dev/search/all_8.js
/usr/share/doc/libpmemobj++-dev/search/all_9.html
/usr/share/doc/libpmemobj++-dev/search/all_9.js
/usr/share/doc/libpmemobj++-dev/search/all_a.html
/usr/share/doc/libpmemobj++-dev/search/all_a.js
/usr/share/doc/libpmemobj++-dev/search/all_b.html
/usr/share/doc/libpmemobj++-dev/search/all_b.js
/usr/share/doc/libpmemobj++-dev/search/all_c.html
/usr/share/doc/libpmemobj++-dev/search/all_c.js
/usr/share/doc/libpmemobj++-dev/search/all_d.html
/usr/share/doc/libpmemobj++-dev/search/all_d.js
/usr/share/doc/libpmemobj++-dev/search/all_e.html
/usr/share/doc/libpmemobj++-dev/search/all_e.js
/usr/share/doc/libpmemobj++-dev/search/all_f.html
/usr/share/doc/libpmemobj++-dev/search/all_f.js
/usr/share/doc/libpmemobj++-dev/search/classes_0.html
/usr/share/doc/libpmemobj++-dev/search/classes_0.js
/usr/share/doc/libpmemobj++-dev/search/classes_1.html
/usr/share/doc/libpmemobj++-dev/search/classes_1.js
/usr/share/doc/libpmemobj++-dev/search/classes_2.html
/usr/share/doc/libpmemobj++-dev/search/classes_2.js
/usr/share/doc/libpmemobj++-dev/search/classes_3.html
/usr/share/doc/libpmemobj++-dev/search/classes_3.js
/usr/share/doc/libpmemobj++-dev/search/classes_4.html
/usr/share/doc/libpmemobj++-dev/search/classes_4.js
/usr/share/doc/libpmemobj++-dev/search/classes_5.html
/usr/share/doc/libpmemobj++-dev/search/classes_5.js
/usr/share/doc/libpmemobj++-dev/search/classes_6.html
/usr/share/doc/libpmemobj++-dev/search/classes_6.js
/usr/share/doc/libpmemobj++-dev/search/classes_7.html
/usr/share/doc/libpmemobj++-dev/search/classes_7.js
/usr/share/doc/libpmemobj++-dev/search/classes_8.html
/usr/share/doc/libpmemobj++-dev/search/classes_8.js
/usr/share/doc/libpmemobj++-dev/search/classes_9.html
/usr/share/doc/libpmemobj++-dev/search/classes_9.js
/usr/share/doc/libpmemobj++-dev/search/close.png
/usr/share/doc/libpmemobj++-dev/search/files_0.html
/usr/share/doc/libpmemobj++-dev/search/files_0.js
/usr/share/doc/libpmemobj++-dev/search/files_1.html
/usr/share/doc/libpmemobj++-dev/search/files_1.js
/usr/share/doc/libpmemobj++-dev/search/files_2.html
/usr/share/doc/libpmemobj++-dev/search/files_2.js
/usr/share/doc/libpmemobj++-dev/search/files_3.html
/usr/share/doc/libpmemobj++-dev/search/files_3.js
/usr/share/doc/libpmemobj++-dev/search/files_4.html
/usr/share/doc/libpmemobj++-dev/search/files_4.js
/usr/share/doc/libpmemobj++-dev/search/files_5.html
/usr/share/doc/libpmemobj++-dev/search/files_5.js
/usr/share/doc/libpmemobj++-dev/search/files_6.html
/usr/share/doc/libpmemobj++-dev/search/files_6.js
/usr/share/doc/libpmemobj++-dev/search/files_7.html
/usr/share/doc/libpmemobj++-dev/search/files_7.js
/usr/share/doc/libpmemobj++-dev/search/files_8.html
/usr/share/doc/libpmemobj++-dev/search/files_8.js
/usr/share/doc/libpmemobj++-dev/search/functions_0.html
/usr/share/doc/libpmemobj++-dev/search/functions_0.js
/usr/share/doc/libpmemobj++-dev/search/functions_1.html
/usr/share/doc/libpmemobj++-dev/search/functions_1.js
/usr/share/doc/libpmemobj++-dev/search/functions_10.html
/usr/share/doc/libpmemobj++-dev/search/functions_10.js
/usr/share/doc/libpmemobj++-dev/search/functions_2.html
/usr/share/doc/libpmemobj++-dev/search/functions_2.js
/usr/share/doc/libpmemobj++-dev/search/functions_3.html
/usr/share/doc/libpmemobj++-dev/search/functions_3.js
/usr/share/doc/libpmemobj++-dev/search/functions_4.html
/usr/share/doc/libpmemobj++-dev/search/functions_4.js
/usr/share/doc/libpmemobj++-dev/search/functions_5.html
/usr/share/doc/libpmemobj++-dev/search/functions_5.js
/usr/share/doc/libpmemobj++-dev/search/functions_6.html
/usr/share/doc/libpmemobj++-dev/search/functions_6.js
/usr/share/doc/libpmemobj++-dev/search/functions_7.html
/usr/share/doc/libpmemobj++-dev/search/functions_7.js
/usr/share/doc/libpmemobj++-dev/search/functions_8.html
/usr/share/doc/libpmemobj++-dev/search/functions_8.js
/usr/share/doc/libpmemobj++-dev/search/functions_9.html
/usr/share/doc/libpmemobj++-dev/search/functions_9.js
/usr/share/doc/libpmemobj++-dev/search/functions_a.html
/usr/share/doc/libpmemobj++-dev/search/functions_a.js
/usr/share/doc/libpmemobj++-dev/search/functions_b.html
/usr/share/doc/libpmemobj++-dev/search/functions_b.js
/usr/share/doc/libpmemobj++-dev/search/functions_c.html
/usr/share/doc/libpmemobj++-dev/search/functions_c.js
/usr/share/doc/libpmemobj++-dev/search/functions_d.html
/usr/share/doc/libpmemobj++-dev/search/functions_d.js
/usr/share/doc/libpmemobj++-dev/search/functions_e.html
/usr/share/doc/libpmemobj++-dev/search/functions_e.js
/usr/share/doc/libpmemobj++-dev/search/functions_f.html
/usr/share/doc/libpmemobj++-dev/search/functions_f.js
/usr/share/doc/libpmemobj++-dev/search/mag_sel.png
/usr/share/doc/libpmemobj++-dev/search/nomatches.html
/usr/share/doc/libpmemobj++-dev/search/pages_0.html
/usr/share/doc/libpmemobj++-dev/search/pages_0.js
/usr/share/doc/libpmemobj++-dev/search/search.css
/usr/share/doc/libpmemobj++-dev/search/search.js
/usr/share/doc/libpmemobj++-dev/search/search_l.png
/usr/share/doc/libpmemobj++-dev/search/search_m.png
/usr/share/doc/libpmemobj++-dev/search/search_r.png
/usr/share/doc/libpmemobj++-dev/search/searchdata.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_0.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_0.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_1.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_1.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_2.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_2.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_3.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_3.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_4.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_4.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_5.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_5.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_6.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_6.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_7.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_7.js
/usr/share/doc/libpmemobj++-dev/search/variables_0.html
/usr/share/doc/libpmemobj++-dev/search/variables_0.js
/usr/share/doc/libpmemobj++-dev/search/variables_1.html
/usr/share/doc/libpmemobj++-dev/search/variables_1.js
/usr/share/doc/libpmemobj++-dev/shared__mutex_8hpp.html
/usr/share/doc/libpmemobj++-dev/shared__mutex_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/specialization_8hpp.html
/usr/share/doc/libpmemobj++-dev/specialization_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/splitbar.png
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1allocator_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1allocator_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1object__traits_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1object__traits_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1object__traits_3_01void_01_4_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1object__traits_3_01void_01_4_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1standard__alloc__policy_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1standard__alloc__policy_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1standard__alloc__policy_3_01void_01_4_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1standard__alloc__policy_3_01void_01_4_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/sync_off.png
/usr/share/doc/libpmemobj++-dev/sync_on.png
/usr/share/doc/libpmemobj++-dev/tab_a.png
/usr/share/doc/libpmemobj++-dev/tab_b.png
/usr/share/doc/libpmemobj++-dev/tab_h.png
/usr/share/doc/libpmemobj++-dev/tab_s.png
/usr/share/doc/libpmemobj++-dev/tabs.css
/usr/share/doc/libpmemobj++-dev/timed__mutex_8hpp.html
/usr/share/doc/libpmemobj++-dev/timed__mutex_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/transaction_8hpp.html
/usr/share/doc/libpmemobj++-dev/transaction_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/utils_8hpp.html
/usr/share/doc/libpmemobj++-dev/utils_8hpp_source.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpmem.so.1
/usr/lib64/libpmem.so.1.0.0
/usr/lib64/libpmemblk.so.1
/usr/lib64/libpmemblk.so.1.0.0
/usr/lib64/libpmemcto.so.1
/usr/lib64/libpmemcto.so.1.0.0
/usr/lib64/libpmemlog.so.1
/usr/lib64/libpmemlog.so.1.0.0
/usr/lib64/libpmemobj.so.1
/usr/lib64/libpmemobj.so.1.0.0
/usr/lib64/libpmempool.so.1
/usr/lib64/libpmempool.so.1.0.0
/usr/lib64/libvmem.so.1
/usr/lib64/libvmem.so.1.0.0
/usr/lib64/libvmmalloc.so.1
/usr/lib64/libvmmalloc.so.1.0.0
/usr/lib64/pmdk_debug/libpmem.so
/usr/lib64/pmdk_debug/libpmem.so.1
/usr/lib64/pmdk_debug/libpmem.so.1.0.0
/usr/lib64/pmdk_debug/libpmemblk.so
/usr/lib64/pmdk_debug/libpmemblk.so.1
/usr/lib64/pmdk_debug/libpmemblk.so.1.0.0
/usr/lib64/pmdk_debug/libpmemcto.so
/usr/lib64/pmdk_debug/libpmemcto.so.1
/usr/lib64/pmdk_debug/libpmemcto.so.1.0.0
/usr/lib64/pmdk_debug/libpmemlog.so
/usr/lib64/pmdk_debug/libpmemlog.so.1
/usr/lib64/pmdk_debug/libpmemlog.so.1.0.0
/usr/lib64/pmdk_debug/libpmemobj.so
/usr/lib64/pmdk_debug/libpmemobj.so.1
/usr/lib64/pmdk_debug/libpmemobj.so.1.0.0
/usr/lib64/pmdk_debug/libpmempool.so
/usr/lib64/pmdk_debug/libpmempool.so.1
/usr/lib64/pmdk_debug/libpmempool.so.1.0.0
/usr/lib64/pmdk_debug/libvmem.so
/usr/lib64/pmdk_debug/libvmem.so.1
/usr/lib64/pmdk_debug/libvmem.so.1.0.0
/usr/lib64/pmdk_debug/libvmmalloc.so
/usr/lib64/pmdk_debug/libvmmalloc.so.1
/usr/lib64/pmdk_debug/libvmmalloc.so.1.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/pmdk/LICENSE
/usr/share/doc/pmdk/src_jemalloc_COPYING
/usr/share/doc/pmdk/src_windows_getopt_LICENSE.txt
/usr/share/doc/pmdk/src_windows_setup_license.rtf

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/pmempool-check.1.gz
/usr/share/man/man1/pmempool-convert.1.gz
/usr/share/man/man1/pmempool-create.1.gz
/usr/share/man/man1/pmempool-dump.1.gz
/usr/share/man/man1/pmempool-info.1.gz
/usr/share/man/man1/pmempool-rm.1.gz
/usr/share/man/man1/pmempool-sync.1.gz
/usr/share/man/man1/pmempool-transform.1.gz
/usr/share/man/man1/pmempool.1.gz
/usr/share/man/man5/poolset.5.gz
/usr/share/man/man7/libpmem.7.gz
/usr/share/man/man7/libpmemblk.7.gz
/usr/share/man/man7/libpmemcto.7.gz
/usr/share/man/man7/libpmemlog.7.gz
/usr/share/man/man7/libpmemobj.7.gz
/usr/share/man/man7/libpmempool.7.gz
/usr/share/man/man7/libvmem.7.gz
/usr/share/man/man7/libvmmalloc.7.gz
