#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pmdk
Version  : 1.4
Release  : 2
URL      : https://github.com/pmem/pmdk/archive/1.4.tar.gz
Source0  : https://github.com/pmem/pmdk/archive/1.4.tar.gz
Summary  : libvmmalloc library from PMDK project
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: pmdk-bin
Requires: pmdk-config
Requires: pmdk-lib
Requires: pmdk-doc
Requires: pmdk-dev
BuildRequires : doxygen

%description
Persistent Memory Development Kit
The scripts found here are used during library development.

%package bin
Summary: bin components for the pmdk package.
Group: Binaries
Requires: pmdk-config

%description bin
bin components for the pmdk package.


%package config
Summary: config components for the pmdk package.
Group: Default

%description config
config components for the pmdk package.


%package dev
Summary: dev components for the pmdk package.
Group: Development
Requires: pmdk-lib
Requires: pmdk-bin
Provides: pmdk-devel

%description dev
dev components for the pmdk package.


%package doc
Summary: doc components for the pmdk package.
Group: Documentation

%description doc
doc components for the pmdk package.


%package lib
Summary: lib components for the pmdk package.
Group: Libraries

%description lib
lib components for the pmdk package.


%prep
%setup -q -n pmdk-1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1524005410
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1524005410
rm -rf %{buildroot}
%make_install prefix=/usr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pmempool

%files config
%defattr(-,root,root,-)
%config /usr/etc/bash_completion.d/pmempool.sh

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/libpmemobj++/allocator.hpp
/usr/include/libpmemobj++/condition_variable.hpp
/usr/include/libpmemobj++/detail/array_traits.hpp
/usr/include/libpmemobj++/detail/check_persistent_ptr_array.hpp
/usr/include/libpmemobj++/detail/common.hpp
/usr/include/libpmemobj++/detail/conversions.hpp
/usr/include/libpmemobj++/detail/integer_sequence.hpp
/usr/include/libpmemobj++/detail/life.hpp
/usr/include/libpmemobj++/detail/make_atomic_impl.hpp
/usr/include/libpmemobj++/detail/persistent_ptr_base.hpp
/usr/include/libpmemobj++/detail/pexceptions.hpp
/usr/include/libpmemobj++/detail/specialization.hpp
/usr/include/libpmemobj++/make_persistent.hpp
/usr/include/libpmemobj++/make_persistent_array.hpp
/usr/include/libpmemobj++/make_persistent_array_atomic.hpp
/usr/include/libpmemobj++/make_persistent_atomic.hpp
/usr/include/libpmemobj++/mutex.hpp
/usr/include/libpmemobj++/p.hpp
/usr/include/libpmemobj++/persistent_ptr.hpp
/usr/include/libpmemobj++/pext.hpp
/usr/include/libpmemobj++/pool.hpp
/usr/include/libpmemobj++/shared_mutex.hpp
/usr/include/libpmemobj++/timed_mutex.hpp
/usr/include/libpmemobj++/transaction.hpp
/usr/include/libpmemobj++/utils.hpp
/usr/include/libpmemobj/action.h
/usr/include/libpmemobj/action_base.h
/usr/include/libpmemobj/atomic.h
/usr/include/libpmemobj/atomic_base.h
/usr/include/libpmemobj/base.h
/usr/include/libpmemobj/ctl.h
/usr/include/libpmemobj/iterator.h
/usr/include/libpmemobj/iterator_base.h
/usr/include/libpmemobj/lists_atomic.h
/usr/include/libpmemobj/lists_atomic_base.h
/usr/include/libpmemobj/pool.h
/usr/include/libpmemobj/pool_base.h
/usr/include/libpmemobj/thread.h
/usr/include/libpmemobj/tx.h
/usr/include/libpmemobj/tx_base.h
/usr/include/libpmemobj/types.h
/usr/lib64/libpmem.so
/usr/lib64/libpmemblk.so
/usr/lib64/libpmemcto.so
/usr/lib64/libpmemlog.so
/usr/lib64/libpmemobj.so
/usr/lib64/libpmempool.so
/usr/lib64/libvmem.so
/usr/lib64/libvmmalloc.so
/usr/lib64/pkgconfig/libpmem.pc
/usr/lib64/pkgconfig/libpmemblk.pc
/usr/lib64/pkgconfig/libpmemcto.pc
/usr/lib64/pkgconfig/libpmemlog.pc
/usr/lib64/pkgconfig/libpmemobj++.pc
/usr/lib64/pkgconfig/libpmemobj.pc
/usr/lib64/pkgconfig/libpmempool.pc
/usr/lib64/pkgconfig/libvmem.pc
/usr/lib64/pkgconfig/libvmmalloc.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man7/*
/usr/share/doc/libpmemobj++-dev/allocator_8hpp.html
/usr/share/doc/libpmemobj++-dev/allocator_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/annotated.html
/usr/share/doc/libpmemobj++-dev/array__traits_8hpp.html
/usr/share/doc/libpmemobj++-dev/array__traits_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/bc_s.png
/usr/share/doc/libpmemobj++-dev/bdwn.png
/usr/share/doc/libpmemobj++-dev/check__persistent__ptr__array_8hpp.html
/usr/share/doc/libpmemobj++-dev/check__persistent__ptr__array_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/classes.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1detail_1_1persistent__ptr__base-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1detail_1_1persistent__ptr__base.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1detail_1_1persistent__ptr__base.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1lock__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1manual__tx__abort.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1allocator-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1allocator.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1condition__variable-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1condition__variable.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1mutex-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1mutex.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1object__traits-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1object__traits.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1object__traits_3_01void_01_4-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1object__traits_3_01void_01_4.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1p-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1p.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1persistent__ptr-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1persistent__ptr.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1persistent__ptr.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool__base-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool__base.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1pool__base.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1shared__mutex-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1shared__mutex.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1standard__alloc__policy-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1standard__alloc__policy.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1standard__alloc__policy_3_01void_01_4-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1standard__alloc__policy_3_01void_01_4.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1timed__mutex-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1timed__mutex.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1automatic-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1automatic.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1automatic_1_1uncaught__exception__counter-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1automatic_1_1uncaught__exception__counter.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1manual-members.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1obj_1_1transaction_1_1manual.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1pool__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__alloc__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__alloc__error.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__error.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__free__error.html
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__free__error.png
/usr/share/doc/libpmemobj++-dev/classpmem_1_1transaction__scope__error.html
/usr/share/doc/libpmemobj++-dev/closed.png
/usr/share/doc/libpmemobj++-dev/common_8hpp.html
/usr/share/doc/libpmemobj++-dev/common_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/condition__variable_8hpp.html
/usr/share/doc/libpmemobj++-dev/condition__variable_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/conversions_8hpp.html
/usr/share/doc/libpmemobj++-dev/conversions_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/dir_038d14fc936bec8624a4a04c58f4b024.html
/usr/share/doc/libpmemobj++-dev/dir_3597dce361ca95183cf430dc6f726499.html
/usr/share/doc/libpmemobj++-dev/dir_47bf87077866604e601e875d1a19ca8e.html
/usr/share/doc/libpmemobj++-dev/dir_504f6d4f810751d4d7da8f2fc8203282.html
/usr/share/doc/libpmemobj++-dev/dir_7d696bcf44522781294232fdadebeeae.html
/usr/share/doc/libpmemobj++-dev/doc.png
/usr/share/doc/libpmemobj++-dev/doxygen.css
/usr/share/doc/libpmemobj++-dev/doxygen.png
/usr/share/doc/libpmemobj++-dev/dynsections.js
/usr/share/doc/libpmemobj++-dev/files.html
/usr/share/doc/libpmemobj++-dev/folderclosed.png
/usr/share/doc/libpmemobj++-dev/folderopen.png
/usr/share/doc/libpmemobj++-dev/functions.html
/usr/share/doc/libpmemobj++-dev/functions_0x7e.html
/usr/share/doc/libpmemobj++-dev/functions_b.html
/usr/share/doc/libpmemobj++-dev/functions_c.html
/usr/share/doc/libpmemobj++-dev/functions_d.html
/usr/share/doc/libpmemobj++-dev/functions_e.html
/usr/share/doc/libpmemobj++-dev/functions_f.html
/usr/share/doc/libpmemobj++-dev/functions_func.html
/usr/share/doc/libpmemobj++-dev/functions_g.html
/usr/share/doc/libpmemobj++-dev/functions_i.html
/usr/share/doc/libpmemobj++-dev/functions_l.html
/usr/share/doc/libpmemobj++-dev/functions_m.html
/usr/share/doc/libpmemobj++-dev/functions_n.html
/usr/share/doc/libpmemobj++-dev/functions_o.html
/usr/share/doc/libpmemobj++-dev/functions_p.html
/usr/share/doc/libpmemobj++-dev/functions_r.html
/usr/share/doc/libpmemobj++-dev/functions_s.html
/usr/share/doc/libpmemobj++-dev/functions_t.html
/usr/share/doc/libpmemobj++-dev/functions_type.html
/usr/share/doc/libpmemobj++-dev/functions_u.html
/usr/share/doc/libpmemobj++-dev/functions_v.html
/usr/share/doc/libpmemobj++-dev/functions_vars.html
/usr/share/doc/libpmemobj++-dev/functions_w.html
/usr/share/doc/libpmemobj++-dev/hierarchy.html
/usr/share/doc/libpmemobj++-dev/index.html
/usr/share/doc/libpmemobj++-dev/integer__sequence_8hpp.html
/usr/share/doc/libpmemobj++-dev/integer__sequence_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/jquery.js
/usr/share/doc/libpmemobj++-dev/life_8hpp.html
/usr/share/doc/libpmemobj++-dev/life_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__atomic__impl_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__atomic__impl_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__persistent_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__persistent_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__persistent__array_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__persistent__array_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__persistent__array__atomic_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__persistent__array__atomic_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/make__persistent__atomic_8hpp.html
/usr/share/doc/libpmemobj++-dev/make__persistent__atomic_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/menu.js
/usr/share/doc/libpmemobj++-dev/menudata.js
/usr/share/doc/libpmemobj++-dev/mutex_8hpp.html
/usr/share/doc/libpmemobj++-dev/mutex_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/nav_f.png
/usr/share/doc/libpmemobj++-dev/nav_g.png
/usr/share/doc/libpmemobj++-dev/nav_h.png
/usr/share/doc/libpmemobj++-dev/open.png
/usr/share/doc/libpmemobj++-dev/p_8hpp.html
/usr/share/doc/libpmemobj++-dev/p_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/persistent__ptr_8hpp.html
/usr/share/doc/libpmemobj++-dev/persistent__ptr_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/persistent__ptr__base_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/pexceptions_8hpp.html
/usr/share/doc/libpmemobj++-dev/pexceptions_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/pext_8hpp.html
/usr/share/doc/libpmemobj++-dev/pext_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/pool_8hpp.html
/usr/share/doc/libpmemobj++-dev/pool_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/search/all_0.html
/usr/share/doc/libpmemobj++-dev/search/all_0.js
/usr/share/doc/libpmemobj++-dev/search/all_1.html
/usr/share/doc/libpmemobj++-dev/search/all_1.js
/usr/share/doc/libpmemobj++-dev/search/all_10.html
/usr/share/doc/libpmemobj++-dev/search/all_10.js
/usr/share/doc/libpmemobj++-dev/search/all_11.html
/usr/share/doc/libpmemobj++-dev/search/all_11.js
/usr/share/doc/libpmemobj++-dev/search/all_12.html
/usr/share/doc/libpmemobj++-dev/search/all_12.js
/usr/share/doc/libpmemobj++-dev/search/all_13.html
/usr/share/doc/libpmemobj++-dev/search/all_13.js
/usr/share/doc/libpmemobj++-dev/search/all_2.html
/usr/share/doc/libpmemobj++-dev/search/all_2.js
/usr/share/doc/libpmemobj++-dev/search/all_3.html
/usr/share/doc/libpmemobj++-dev/search/all_3.js
/usr/share/doc/libpmemobj++-dev/search/all_4.html
/usr/share/doc/libpmemobj++-dev/search/all_4.js
/usr/share/doc/libpmemobj++-dev/search/all_5.html
/usr/share/doc/libpmemobj++-dev/search/all_5.js
/usr/share/doc/libpmemobj++-dev/search/all_6.html
/usr/share/doc/libpmemobj++-dev/search/all_6.js
/usr/share/doc/libpmemobj++-dev/search/all_7.html
/usr/share/doc/libpmemobj++-dev/search/all_7.js
/usr/share/doc/libpmemobj++-dev/search/all_8.html
/usr/share/doc/libpmemobj++-dev/search/all_8.js
/usr/share/doc/libpmemobj++-dev/search/all_9.html
/usr/share/doc/libpmemobj++-dev/search/all_9.js
/usr/share/doc/libpmemobj++-dev/search/all_a.html
/usr/share/doc/libpmemobj++-dev/search/all_a.js
/usr/share/doc/libpmemobj++-dev/search/all_b.html
/usr/share/doc/libpmemobj++-dev/search/all_b.js
/usr/share/doc/libpmemobj++-dev/search/all_c.html
/usr/share/doc/libpmemobj++-dev/search/all_c.js
/usr/share/doc/libpmemobj++-dev/search/all_d.html
/usr/share/doc/libpmemobj++-dev/search/all_d.js
/usr/share/doc/libpmemobj++-dev/search/all_e.html
/usr/share/doc/libpmemobj++-dev/search/all_e.js
/usr/share/doc/libpmemobj++-dev/search/all_f.html
/usr/share/doc/libpmemobj++-dev/search/all_f.js
/usr/share/doc/libpmemobj++-dev/search/classes_0.html
/usr/share/doc/libpmemobj++-dev/search/classes_0.js
/usr/share/doc/libpmemobj++-dev/search/classes_1.html
/usr/share/doc/libpmemobj++-dev/search/classes_1.js
/usr/share/doc/libpmemobj++-dev/search/classes_2.html
/usr/share/doc/libpmemobj++-dev/search/classes_2.js
/usr/share/doc/libpmemobj++-dev/search/classes_3.html
/usr/share/doc/libpmemobj++-dev/search/classes_3.js
/usr/share/doc/libpmemobj++-dev/search/classes_4.html
/usr/share/doc/libpmemobj++-dev/search/classes_4.js
/usr/share/doc/libpmemobj++-dev/search/classes_5.html
/usr/share/doc/libpmemobj++-dev/search/classes_5.js
/usr/share/doc/libpmemobj++-dev/search/classes_6.html
/usr/share/doc/libpmemobj++-dev/search/classes_6.js
/usr/share/doc/libpmemobj++-dev/search/classes_7.html
/usr/share/doc/libpmemobj++-dev/search/classes_7.js
/usr/share/doc/libpmemobj++-dev/search/classes_8.html
/usr/share/doc/libpmemobj++-dev/search/classes_8.js
/usr/share/doc/libpmemobj++-dev/search/classes_9.html
/usr/share/doc/libpmemobj++-dev/search/classes_9.js
/usr/share/doc/libpmemobj++-dev/search/close.png
/usr/share/doc/libpmemobj++-dev/search/files_0.html
/usr/share/doc/libpmemobj++-dev/search/files_0.js
/usr/share/doc/libpmemobj++-dev/search/files_1.html
/usr/share/doc/libpmemobj++-dev/search/files_1.js
/usr/share/doc/libpmemobj++-dev/search/files_2.html
/usr/share/doc/libpmemobj++-dev/search/files_2.js
/usr/share/doc/libpmemobj++-dev/search/files_3.html
/usr/share/doc/libpmemobj++-dev/search/files_3.js
/usr/share/doc/libpmemobj++-dev/search/files_4.html
/usr/share/doc/libpmemobj++-dev/search/files_4.js
/usr/share/doc/libpmemobj++-dev/search/files_5.html
/usr/share/doc/libpmemobj++-dev/search/files_5.js
/usr/share/doc/libpmemobj++-dev/search/files_6.html
/usr/share/doc/libpmemobj++-dev/search/files_6.js
/usr/share/doc/libpmemobj++-dev/search/files_7.html
/usr/share/doc/libpmemobj++-dev/search/files_7.js
/usr/share/doc/libpmemobj++-dev/search/files_8.html
/usr/share/doc/libpmemobj++-dev/search/files_8.js
/usr/share/doc/libpmemobj++-dev/search/functions_0.html
/usr/share/doc/libpmemobj++-dev/search/functions_0.js
/usr/share/doc/libpmemobj++-dev/search/functions_1.html
/usr/share/doc/libpmemobj++-dev/search/functions_1.js
/usr/share/doc/libpmemobj++-dev/search/functions_10.html
/usr/share/doc/libpmemobj++-dev/search/functions_10.js
/usr/share/doc/libpmemobj++-dev/search/functions_2.html
/usr/share/doc/libpmemobj++-dev/search/functions_2.js
/usr/share/doc/libpmemobj++-dev/search/functions_3.html
/usr/share/doc/libpmemobj++-dev/search/functions_3.js
/usr/share/doc/libpmemobj++-dev/search/functions_4.html
/usr/share/doc/libpmemobj++-dev/search/functions_4.js
/usr/share/doc/libpmemobj++-dev/search/functions_5.html
/usr/share/doc/libpmemobj++-dev/search/functions_5.js
/usr/share/doc/libpmemobj++-dev/search/functions_6.html
/usr/share/doc/libpmemobj++-dev/search/functions_6.js
/usr/share/doc/libpmemobj++-dev/search/functions_7.html
/usr/share/doc/libpmemobj++-dev/search/functions_7.js
/usr/share/doc/libpmemobj++-dev/search/functions_8.html
/usr/share/doc/libpmemobj++-dev/search/functions_8.js
/usr/share/doc/libpmemobj++-dev/search/functions_9.html
/usr/share/doc/libpmemobj++-dev/search/functions_9.js
/usr/share/doc/libpmemobj++-dev/search/functions_a.html
/usr/share/doc/libpmemobj++-dev/search/functions_a.js
/usr/share/doc/libpmemobj++-dev/search/functions_b.html
/usr/share/doc/libpmemobj++-dev/search/functions_b.js
/usr/share/doc/libpmemobj++-dev/search/functions_c.html
/usr/share/doc/libpmemobj++-dev/search/functions_c.js
/usr/share/doc/libpmemobj++-dev/search/functions_d.html
/usr/share/doc/libpmemobj++-dev/search/functions_d.js
/usr/share/doc/libpmemobj++-dev/search/functions_e.html
/usr/share/doc/libpmemobj++-dev/search/functions_e.js
/usr/share/doc/libpmemobj++-dev/search/functions_f.html
/usr/share/doc/libpmemobj++-dev/search/functions_f.js
/usr/share/doc/libpmemobj++-dev/search/mag_sel.png
/usr/share/doc/libpmemobj++-dev/search/nomatches.html
/usr/share/doc/libpmemobj++-dev/search/pages_0.html
/usr/share/doc/libpmemobj++-dev/search/pages_0.js
/usr/share/doc/libpmemobj++-dev/search/search.css
/usr/share/doc/libpmemobj++-dev/search/search.js
/usr/share/doc/libpmemobj++-dev/search/search_l.png
/usr/share/doc/libpmemobj++-dev/search/search_m.png
/usr/share/doc/libpmemobj++-dev/search/search_r.png
/usr/share/doc/libpmemobj++-dev/search/searchdata.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_0.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_0.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_1.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_1.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_2.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_2.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_3.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_3.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_4.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_4.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_5.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_5.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_6.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_6.js
/usr/share/doc/libpmemobj++-dev/search/typedefs_7.html
/usr/share/doc/libpmemobj++-dev/search/typedefs_7.js
/usr/share/doc/libpmemobj++-dev/search/variables_0.html
/usr/share/doc/libpmemobj++-dev/search/variables_0.js
/usr/share/doc/libpmemobj++-dev/search/variables_1.html
/usr/share/doc/libpmemobj++-dev/search/variables_1.js
/usr/share/doc/libpmemobj++-dev/shared__mutex_8hpp.html
/usr/share/doc/libpmemobj++-dev/shared__mutex_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/specialization_8hpp.html
/usr/share/doc/libpmemobj++-dev/specialization_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/splitbar.png
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1allocator_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1allocator_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1object__traits_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1object__traits_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1object__traits_3_01void_01_4_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1object__traits_3_01void_01_4_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1standard__alloc__policy_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1standard__alloc__policy_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1standard__alloc__policy_3_01void_01_4_1_1rebind-members.html
/usr/share/doc/libpmemobj++-dev/structpmem_1_1obj_1_1standard__alloc__policy_3_01void_01_4_1_1rebind.html
/usr/share/doc/libpmemobj++-dev/sync_off.png
/usr/share/doc/libpmemobj++-dev/sync_on.png
/usr/share/doc/libpmemobj++-dev/tab_a.png
/usr/share/doc/libpmemobj++-dev/tab_b.png
/usr/share/doc/libpmemobj++-dev/tab_h.png
/usr/share/doc/libpmemobj++-dev/tab_s.png
/usr/share/doc/libpmemobj++-dev/tabs.css
/usr/share/doc/libpmemobj++-dev/timed__mutex_8hpp.html
/usr/share/doc/libpmemobj++-dev/timed__mutex_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/transaction_8hpp.html
/usr/share/doc/libpmemobj++-dev/transaction_8hpp_source.html
/usr/share/doc/libpmemobj++-dev/utils_8hpp.html
/usr/share/doc/libpmemobj++-dev/utils_8hpp_source.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpmem.so.1
/usr/lib64/libpmem.so.1.0.0
/usr/lib64/libpmemblk.so.1
/usr/lib64/libpmemblk.so.1.0.0
/usr/lib64/libpmemcto.so.1
/usr/lib64/libpmemcto.so.1.0.0
/usr/lib64/libpmemlog.so.1
/usr/lib64/libpmemlog.so.1.0.0
/usr/lib64/libpmemobj.so.1
/usr/lib64/libpmemobj.so.1.0.0
/usr/lib64/libpmempool.so.1
/usr/lib64/libpmempool.so.1.0.0
/usr/lib64/libvmem.so.1
/usr/lib64/libvmem.so.1.0.0
/usr/lib64/libvmmalloc.so.1
/usr/lib64/libvmmalloc.so.1.0.0
/usr/lib64/pmdk_debug/libpmem.so
/usr/lib64/pmdk_debug/libpmem.so.1
/usr/lib64/pmdk_debug/libpmem.so.1.0.0
/usr/lib64/pmdk_debug/libpmemblk.so
/usr/lib64/pmdk_debug/libpmemblk.so.1
/usr/lib64/pmdk_debug/libpmemblk.so.1.0.0
/usr/lib64/pmdk_debug/libpmemcto.so
/usr/lib64/pmdk_debug/libpmemcto.so.1
/usr/lib64/pmdk_debug/libpmemcto.so.1.0.0
/usr/lib64/pmdk_debug/libpmemlog.so
/usr/lib64/pmdk_debug/libpmemlog.so.1
/usr/lib64/pmdk_debug/libpmemlog.so.1.0.0
/usr/lib64/pmdk_debug/libpmemobj.so
/usr/lib64/pmdk_debug/libpmemobj.so.1
/usr/lib64/pmdk_debug/libpmemobj.so.1.0.0
/usr/lib64/pmdk_debug/libpmempool.so
/usr/lib64/pmdk_debug/libpmempool.so.1
/usr/lib64/pmdk_debug/libpmempool.so.1.0.0
/usr/lib64/pmdk_debug/libvmem.so
/usr/lib64/pmdk_debug/libvmem.so.1
/usr/lib64/pmdk_debug/libvmem.so.1.0.0
/usr/lib64/pmdk_debug/libvmmalloc.so
/usr/lib64/pmdk_debug/libvmmalloc.so.1
/usr/lib64/pmdk_debug/libvmmalloc.so.1.0.0
