#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pmdk
Version  : 1.5.1
Release  : 13
URL      : https://github.com/pmem/pmdk/archive/1.5.1.tar.gz
Source0  : https://github.com/pmem/pmdk/archive/1.5.1.tar.gz
Summary  : libvmmalloc library from PMDK project
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: pmdk-bin = %{version}-%{release}
Requires: pmdk-data = %{version}-%{release}
Requires: pmdk-lib = %{version}-%{release}
Requires: pmdk-license = %{version}-%{release}
Requires: pmdk-man = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : ndctl-dev

%description
Persistent Memory Development Kit
The scripts found here are used during library development.

%package bin
Summary: bin components for the pmdk package.
Group: Binaries
Requires: pmdk-data = %{version}-%{release}
Requires: pmdk-license = %{version}-%{release}

%description bin
bin components for the pmdk package.


%package data
Summary: data components for the pmdk package.
Group: Data

%description data
data components for the pmdk package.


%package dev
Summary: dev components for the pmdk package.
Group: Development
Requires: pmdk-lib = %{version}-%{release}
Requires: pmdk-bin = %{version}-%{release}
Requires: pmdk-data = %{version}-%{release}
Provides: pmdk-devel = %{version}-%{release}
Requires: pmdk = %{version}-%{release}

%description dev
dev components for the pmdk package.


%package lib
Summary: lib components for the pmdk package.
Group: Libraries
Requires: pmdk-data = %{version}-%{release}
Requires: pmdk-license = %{version}-%{release}

%description lib
lib components for the pmdk package.


%package license
Summary: license components for the pmdk package.
Group: Default

%description license
license components for the pmdk package.


%package man
Summary: man components for the pmdk package.
Group: Default

%description man
man components for the pmdk package.


%prep
%setup -q -n pmdk-1.5.1
cd %{_builddir}/pmdk-1.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604605388
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1604605388
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pmdk
cp %{_builddir}/pmdk-1.5.1/LICENSE %{buildroot}/usr/share/package-licenses/pmdk/4b07e66cc7925c2a6e0c68d25b78f90c9be4fc68
cp %{_builddir}/pmdk-1.5.1/src/jemalloc/COPYING %{buildroot}/usr/share/package-licenses/pmdk/3dbfb3fe97c5e5d656cd3ee22d970e7e73a7a6c6
cp %{_builddir}/pmdk-1.5.1/src/windows/getopt/LICENSE.txt %{buildroot}/usr/share/package-licenses/pmdk/b37189216d7244b1bfd4a8c1e73085469c2ba9a6
%make_install prefix=/usr bashcompdir=/usr/share/bash-completion/completions

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/daxio
/usr/bin/pmempool
/usr/bin/pmreorder

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/pmempool
/usr/share/pmreorder/binaryoutputhandler.py
/usr/share/pmreorder/consistencycheckwrap.py
/usr/share/pmreorder/loggingfacility.py
/usr/share/pmreorder/markerparser.py
/usr/share/pmreorder/memoryoperations.py
/usr/share/pmreorder/operationfactory.py
/usr/share/pmreorder/opscontext.py
/usr/share/pmreorder/pmreorder.py
/usr/share/pmreorder/reorderengines.py
/usr/share/pmreorder/reorderexceptions.py
/usr/share/pmreorder/statemachine.py
/usr/share/pmreorder/utils.py

%files dev
%defattr(-,root,root,-)
/usr/include/libpmem.h
/usr/include/libpmemblk.h
/usr/include/libpmemlog.h
/usr/include/libpmemobj.h
/usr/include/libpmemobj/action.h
/usr/include/libpmemobj/action_base.h
/usr/include/libpmemobj/atomic.h
/usr/include/libpmemobj/atomic_base.h
/usr/include/libpmemobj/base.h
/usr/include/libpmemobj/ctl.h
/usr/include/libpmemobj/iterator.h
/usr/include/libpmemobj/iterator_base.h
/usr/include/libpmemobj/lists_atomic.h
/usr/include/libpmemobj/lists_atomic_base.h
/usr/include/libpmemobj/pool.h
/usr/include/libpmemobj/pool_base.h
/usr/include/libpmemobj/thread.h
/usr/include/libpmemobj/tx.h
/usr/include/libpmemobj/tx_base.h
/usr/include/libpmemobj/types.h
/usr/include/libpmempool.h
/usr/include/libvmem.h
/usr/include/libvmmalloc.h
/usr/lib64/libpmem.so
/usr/lib64/libpmemblk.so
/usr/lib64/libpmemlog.so
/usr/lib64/libpmemobj.so
/usr/lib64/libpmempool.so
/usr/lib64/libvmem.so
/usr/lib64/libvmmalloc.so
/usr/lib64/pkgconfig/libpmem.pc
/usr/lib64/pkgconfig/libpmemblk.pc
/usr/lib64/pkgconfig/libpmemlog.pc
/usr/lib64/pkgconfig/libpmemobj.pc
/usr/lib64/pkgconfig/libpmempool.pc
/usr/lib64/pkgconfig/libvmem.pc
/usr/lib64/pkgconfig/libvmmalloc.pc
/usr/share/man/man3/d_ro.3.gz
/usr/share/man/man3/d_rw.3.gz
/usr/share/man/man3/direct_ro.3.gz
/usr/share/man/man3/direct_rw.3.gz
/usr/share/man/man3/oid_equals.3.gz
/usr/share/man/man3/oid_instanceof.3.gz
/usr/share/man/man3/oid_is_null.3.gz
/usr/share/man/man3/pmem_check_version.3.gz
/usr/share/man/man3/pmem_deep_drain.3.gz
/usr/share/man/man3/pmem_deep_flush.3.gz
/usr/share/man/man3/pmem_deep_persist.3.gz
/usr/share/man/man3/pmem_drain.3.gz
/usr/share/man/man3/pmem_errormsg.3.gz
/usr/share/man/man3/pmem_flush.3.gz
/usr/share/man/man3/pmem_has_auto_flush.3.gz
/usr/share/man/man3/pmem_has_hw_drain.3.gz
/usr/share/man/man3/pmem_is_pmem.3.gz
/usr/share/man/man3/pmem_map_file.3.gz
/usr/share/man/man3/pmem_memcpy.3.gz
/usr/share/man/man3/pmem_memcpy_nodrain.3.gz
/usr/share/man/man3/pmem_memcpy_persist.3.gz
/usr/share/man/man3/pmem_memmove.3.gz
/usr/share/man/man3/pmem_memmove_nodrain.3.gz
/usr/share/man/man3/pmem_memmove_persist.3.gz
/usr/share/man/man3/pmem_memset.3.gz
/usr/share/man/man3/pmem_memset_nodrain.3.gz
/usr/share/man/man3/pmem_memset_persist.3.gz
/usr/share/man/man3/pmem_msync.3.gz
/usr/share/man/man3/pmem_persist.3.gz
/usr/share/man/man3/pmem_unmap.3.gz
/usr/share/man/man3/pmemblk_bsize.3.gz
/usr/share/man/man3/pmemblk_check.3.gz
/usr/share/man/man3/pmemblk_check_version.3.gz
/usr/share/man/man3/pmemblk_close.3.gz
/usr/share/man/man3/pmemblk_create.3.gz
/usr/share/man/man3/pmemblk_ctl_exec.3.gz
/usr/share/man/man3/pmemblk_ctl_get.3.gz
/usr/share/man/man3/pmemblk_ctl_set.3.gz
/usr/share/man/man3/pmemblk_errormsg.3.gz
/usr/share/man/man3/pmemblk_nblock.3.gz
/usr/share/man/man3/pmemblk_open.3.gz
/usr/share/man/man3/pmemblk_read.3.gz
/usr/share/man/man3/pmemblk_set_error.3.gz
/usr/share/man/man3/pmemblk_set_funcs.3.gz
/usr/share/man/man3/pmemblk_set_zero.3.gz
/usr/share/man/man3/pmemblk_write.3.gz
/usr/share/man/man3/pmemlog_append.3.gz
/usr/share/man/man3/pmemlog_appendv.3.gz
/usr/share/man/man3/pmemlog_check.3.gz
/usr/share/man/man3/pmemlog_check_version.3.gz
/usr/share/man/man3/pmemlog_close.3.gz
/usr/share/man/man3/pmemlog_create.3.gz
/usr/share/man/man3/pmemlog_ctl_exec.3.gz
/usr/share/man/man3/pmemlog_ctl_get.3.gz
/usr/share/man/man3/pmemlog_ctl_set.3.gz
/usr/share/man/man3/pmemlog_errormsg.3.gz
/usr/share/man/man3/pmemlog_nbyte.3.gz
/usr/share/man/man3/pmemlog_open.3.gz
/usr/share/man/man3/pmemlog_rewind.3.gz
/usr/share/man/man3/pmemlog_set_funcs.3.gz
/usr/share/man/man3/pmemlog_tell.3.gz
/usr/share/man/man3/pmemlog_walk.3.gz
/usr/share/man/man3/pmemobj_action.3.gz
/usr/share/man/man3/pmemobj_alloc.3.gz
/usr/share/man/man3/pmemobj_alloc_usable_size.3.gz
/usr/share/man/man3/pmemobj_cancel.3.gz
/usr/share/man/man3/pmemobj_check.3.gz
/usr/share/man/man3/pmemobj_check_version.3.gz
/usr/share/man/man3/pmemobj_close.3.gz
/usr/share/man/man3/pmemobj_cond_broadcast.3.gz
/usr/share/man/man3/pmemobj_cond_signal.3.gz
/usr/share/man/man3/pmemobj_cond_timedwait.3.gz
/usr/share/man/man3/pmemobj_cond_wait.3.gz
/usr/share/man/man3/pmemobj_cond_zero.3.gz
/usr/share/man/man3/pmemobj_create.3.gz
/usr/share/man/man3/pmemobj_ctl_exec.3.gz
/usr/share/man/man3/pmemobj_ctl_get.3.gz
/usr/share/man/man3/pmemobj_ctl_set.3.gz
/usr/share/man/man3/pmemobj_defer_free.3.gz
/usr/share/man/man3/pmemobj_direct.3.gz
/usr/share/man/man3/pmemobj_drain.3.gz
/usr/share/man/man3/pmemobj_errormsg.3.gz
/usr/share/man/man3/pmemobj_f_mem_nodrain.3.gz
/usr/share/man/man3/pmemobj_f_mem_noflush.3.gz
/usr/share/man/man3/pmemobj_f_mem_nontemporal.3.gz
/usr/share/man/man3/pmemobj_f_mem_temporal.3.gz
/usr/share/man/man3/pmemobj_f_mem_wb.3.gz
/usr/share/man/man3/pmemobj_f_mem_wc.3.gz
/usr/share/man/man3/pmemobj_f_relaxed.3.gz
/usr/share/man/man3/pmemobj_first.3.gz
/usr/share/man/man3/pmemobj_flush.3.gz
/usr/share/man/man3/pmemobj_free.3.gz
/usr/share/man/man3/pmemobj_list_insert.3.gz
/usr/share/man/man3/pmemobj_list_insert_new.3.gz
/usr/share/man/man3/pmemobj_list_move.3.gz
/usr/share/man/man3/pmemobj_list_remove.3.gz
/usr/share/man/man3/pmemobj_memcpy.3.gz
/usr/share/man/man3/pmemobj_memcpy_persist.3.gz
/usr/share/man/man3/pmemobj_memmove.3.gz
/usr/share/man/man3/pmemobj_memset.3.gz
/usr/share/man/man3/pmemobj_memset_persist.3.gz
/usr/share/man/man3/pmemobj_mutex_lock.3.gz
/usr/share/man/man3/pmemobj_mutex_timedlock.3.gz
/usr/share/man/man3/pmemobj_mutex_trylock.3.gz
/usr/share/man/man3/pmemobj_mutex_unlock.3.gz
/usr/share/man/man3/pmemobj_mutex_zero.3.gz
/usr/share/man/man3/pmemobj_next.3.gz
/usr/share/man/man3/pmemobj_oid.3.gz
/usr/share/man/man3/pmemobj_open.3.gz
/usr/share/man/man3/pmemobj_persist.3.gz
/usr/share/man/man3/pmemobj_pool_by_oid.3.gz
/usr/share/man/man3/pmemobj_pool_by_ptr.3.gz
/usr/share/man/man3/pmemobj_publish.3.gz
/usr/share/man/man3/pmemobj_realloc.3.gz
/usr/share/man/man3/pmemobj_reserve.3.gz
/usr/share/man/man3/pmemobj_root.3.gz
/usr/share/man/man3/pmemobj_root_construct.3.gz
/usr/share/man/man3/pmemobj_root_size.3.gz
/usr/share/man/man3/pmemobj_rwlock_rdlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_timedrdlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_timedwrlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_tryrdlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_trywrlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_unlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_wrlock.3.gz
/usr/share/man/man3/pmemobj_rwlock_zero.3.gz
/usr/share/man/man3/pmemobj_set_funcs.3.gz
/usr/share/man/man3/pmemobj_set_value.3.gz
/usr/share/man/man3/pmemobj_strdup.3.gz
/usr/share/man/man3/pmemobj_tx_abort.3.gz
/usr/share/man/man3/pmemobj_tx_add_range.3.gz
/usr/share/man/man3/pmemobj_tx_add_range_direct.3.gz
/usr/share/man/man3/pmemobj_tx_alloc.3.gz
/usr/share/man/man3/pmemobj_tx_begin.3.gz
/usr/share/man/man3/pmemobj_tx_commit.3.gz
/usr/share/man/man3/pmemobj_tx_end.3.gz
/usr/share/man/man3/pmemobj_tx_errno.3.gz
/usr/share/man/man3/pmemobj_tx_free.3.gz
/usr/share/man/man3/pmemobj_tx_lock.3.gz
/usr/share/man/man3/pmemobj_tx_process.3.gz
/usr/share/man/man3/pmemobj_tx_publish.3.gz
/usr/share/man/man3/pmemobj_tx_realloc.3.gz
/usr/share/man/man3/pmemobj_tx_stage.3.gz
/usr/share/man/man3/pmemobj_tx_strdup.3.gz
/usr/share/man/man3/pmemobj_tx_wcsdup.3.gz
/usr/share/man/man3/pmemobj_tx_xadd_range.3.gz
/usr/share/man/man3/pmemobj_tx_xadd_range_direct.3.gz
/usr/share/man/man3/pmemobj_tx_xalloc.3.gz
/usr/share/man/man3/pmemobj_tx_zalloc.3.gz
/usr/share/man/man3/pmemobj_tx_zrealloc.3.gz
/usr/share/man/man3/pmemobj_type_num.3.gz
/usr/share/man/man3/pmemobj_volatile.3.gz
/usr/share/man/man3/pmemobj_wcsdup.3.gz
/usr/share/man/man3/pmemobj_xalloc.3.gz
/usr/share/man/man3/pmemobj_xflush.3.gz
/usr/share/man/man3/pmemobj_xpersist.3.gz
/usr/share/man/man3/pmemobj_xreserve.3.gz
/usr/share/man/man3/pmemobj_zalloc.3.gz
/usr/share/man/man3/pmemobj_zrealloc.3.gz
/usr/share/man/man3/pmempool_check.3.gz
/usr/share/man/man3/pmempool_check_end.3.gz
/usr/share/man/man3/pmempool_check_init.3.gz
/usr/share/man/man3/pmempool_check_version.3.gz
/usr/share/man/man3/pmempool_errormsg.3.gz
/usr/share/man/man3/pmempool_feature_disable.3.gz
/usr/share/man/man3/pmempool_feature_enable.3.gz
/usr/share/man/man3/pmempool_feature_query.3.gz
/usr/share/man/man3/pmempool_rm.3.gz
/usr/share/man/man3/pmempool_sync.3.gz
/usr/share/man/man3/pmempool_transform.3.gz
/usr/share/man/man3/pobj_alloc.3.gz
/usr/share/man/man3/pobj_first.3.gz
/usr/share/man/man3/pobj_first_type_num.3.gz
/usr/share/man/man3/pobj_foreach.3.gz
/usr/share/man/man3/pobj_foreach_safe.3.gz
/usr/share/man/man3/pobj_foreach_safe_type.3.gz
/usr/share/man/man3/pobj_foreach_type.3.gz
/usr/share/man/man3/pobj_free.3.gz
/usr/share/man/man3/pobj_layout_begin.3.gz
/usr/share/man/man3/pobj_layout_end.3.gz
/usr/share/man/man3/pobj_layout_name.3.gz
/usr/share/man/man3/pobj_layout_root.3.gz
/usr/share/man/man3/pobj_layout_toid.3.gz
/usr/share/man/man3/pobj_layout_types_num.3.gz
/usr/share/man/man3/pobj_list_empty.3.gz
/usr/share/man/man3/pobj_list_entry.3.gz
/usr/share/man/man3/pobj_list_first.3.gz
/usr/share/man/man3/pobj_list_foreach.3.gz
/usr/share/man/man3/pobj_list_foreach_reverse.3.gz
/usr/share/man/man3/pobj_list_head.3.gz
/usr/share/man/man3/pobj_list_insert_after.3.gz
/usr/share/man/man3/pobj_list_insert_before.3.gz
/usr/share/man/man3/pobj_list_insert_head.3.gz
/usr/share/man/man3/pobj_list_insert_new_after.3.gz
/usr/share/man/man3/pobj_list_insert_new_before.3.gz
/usr/share/man/man3/pobj_list_insert_new_head.3.gz
/usr/share/man/man3/pobj_list_insert_new_tail.3.gz
/usr/share/man/man3/pobj_list_insert_tail.3.gz
/usr/share/man/man3/pobj_list_last.3.gz
/usr/share/man/man3/pobj_list_move_element_after.3.gz
/usr/share/man/man3/pobj_list_move_element_before.3.gz
/usr/share/man/man3/pobj_list_move_element_head.3.gz
/usr/share/man/man3/pobj_list_move_element_tail.3.gz
/usr/share/man/man3/pobj_list_next.3.gz
/usr/share/man/man3/pobj_list_prev.3.gz
/usr/share/man/man3/pobj_list_remove.3.gz
/usr/share/man/man3/pobj_list_remove_free.3.gz
/usr/share/man/man3/pobj_new.3.gz
/usr/share/man/man3/pobj_next.3.gz
/usr/share/man/man3/pobj_next_type_num.3.gz
/usr/share/man/man3/pobj_realloc.3.gz
/usr/share/man/man3/pobj_reserve_alloc.3.gz
/usr/share/man/man3/pobj_reserve_new.3.gz
/usr/share/man/man3/pobj_root.3.gz
/usr/share/man/man3/pobj_xreserve_alloc.3.gz
/usr/share/man/man3/pobj_xreserve_new.3.gz
/usr/share/man/man3/pobj_zalloc.3.gz
/usr/share/man/man3/pobj_znew.3.gz
/usr/share/man/man3/pobj_zrealloc.3.gz
/usr/share/man/man3/toid.3.gz
/usr/share/man/man3/toid_assign.3.gz
/usr/share/man/man3/toid_declare.3.gz
/usr/share/man/man3/toid_declare_root.3.gz
/usr/share/man/man3/toid_equals.3.gz
/usr/share/man/man3/toid_is_null.3.gz
/usr/share/man/man3/toid_offsetof.3.gz
/usr/share/man/man3/toid_type_num.3.gz
/usr/share/man/man3/toid_type_num_of.3.gz
/usr/share/man/man3/toid_typeof.3.gz
/usr/share/man/man3/toid_valid.3.gz
/usr/share/man/man3/tx_add.3.gz
/usr/share/man/man3/tx_add_direct.3.gz
/usr/share/man/man3/tx_add_field.3.gz
/usr/share/man/man3/tx_add_field_direct.3.gz
/usr/share/man/man3/tx_alloc.3.gz
/usr/share/man/man3/tx_begin.3.gz
/usr/share/man/man3/tx_begin_cb.3.gz
/usr/share/man/man3/tx_begin_param.3.gz
/usr/share/man/man3/tx_end.3.gz
/usr/share/man/man3/tx_finally.3.gz
/usr/share/man/man3/tx_free.3.gz
/usr/share/man/man3/tx_memcpy.3.gz
/usr/share/man/man3/tx_memset.3.gz
/usr/share/man/man3/tx_new.3.gz
/usr/share/man/man3/tx_onabort.3.gz
/usr/share/man/man3/tx_oncommit.3.gz
/usr/share/man/man3/tx_realloc.3.gz
/usr/share/man/man3/tx_set.3.gz
/usr/share/man/man3/tx_set_direct.3.gz
/usr/share/man/man3/tx_strdup.3.gz
/usr/share/man/man3/tx_wcsdup.3.gz
/usr/share/man/man3/tx_xadd.3.gz
/usr/share/man/man3/tx_xadd_direct.3.gz
/usr/share/man/man3/tx_xadd_field.3.gz
/usr/share/man/man3/tx_xadd_field_direct.3.gz
/usr/share/man/man3/tx_xalloc.3.gz
/usr/share/man/man3/tx_zalloc.3.gz
/usr/share/man/man3/tx_znew.3.gz
/usr/share/man/man3/tx_zrealloc.3.gz
/usr/share/man/man3/vmem_aligned_alloc.3.gz
/usr/share/man/man3/vmem_calloc.3.gz
/usr/share/man/man3/vmem_check.3.gz
/usr/share/man/man3/vmem_check_version.3.gz
/usr/share/man/man3/vmem_create.3.gz
/usr/share/man/man3/vmem_create_in_region.3.gz
/usr/share/man/man3/vmem_delete.3.gz
/usr/share/man/man3/vmem_errormsg.3.gz
/usr/share/man/man3/vmem_free.3.gz
/usr/share/man/man3/vmem_malloc.3.gz
/usr/share/man/man3/vmem_malloc_usable_size.3.gz
/usr/share/man/man3/vmem_realloc.3.gz
/usr/share/man/man3/vmem_set_funcs.3.gz
/usr/share/man/man3/vmem_stats_print.3.gz
/usr/share/man/man3/vmem_strdup.3.gz
/usr/share/man/man3/vmem_wcsdup.3.gz

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpmem.so.1
/usr/lib64/libpmem.so.1.0.0
/usr/lib64/libpmemblk.so.1
/usr/lib64/libpmemblk.so.1.0.0
/usr/lib64/libpmemlog.so.1
/usr/lib64/libpmemlog.so.1.0.0
/usr/lib64/libpmemobj.so.1
/usr/lib64/libpmemobj.so.1.0.0
/usr/lib64/libpmempool.so.1
/usr/lib64/libpmempool.so.1.0.0
/usr/lib64/libvmem.so.1
/usr/lib64/libvmem.so.1.0.0
/usr/lib64/libvmmalloc.so.1
/usr/lib64/libvmmalloc.so.1.0.0
/usr/lib64/pmdk_debug/libpmem.so
/usr/lib64/pmdk_debug/libpmem.so.1
/usr/lib64/pmdk_debug/libpmem.so.1.0.0
/usr/lib64/pmdk_debug/libpmemblk.so
/usr/lib64/pmdk_debug/libpmemblk.so.1
/usr/lib64/pmdk_debug/libpmemblk.so.1.0.0
/usr/lib64/pmdk_debug/libpmemlog.so
/usr/lib64/pmdk_debug/libpmemlog.so.1
/usr/lib64/pmdk_debug/libpmemlog.so.1.0.0
/usr/lib64/pmdk_debug/libpmemobj.so
/usr/lib64/pmdk_debug/libpmemobj.so.1
/usr/lib64/pmdk_debug/libpmemobj.so.1.0.0
/usr/lib64/pmdk_debug/libpmempool.so
/usr/lib64/pmdk_debug/libpmempool.so.1
/usr/lib64/pmdk_debug/libpmempool.so.1.0.0
/usr/lib64/pmdk_debug/libvmem.so
/usr/lib64/pmdk_debug/libvmem.so.1
/usr/lib64/pmdk_debug/libvmem.so.1.0.0
/usr/lib64/pmdk_debug/libvmmalloc.so
/usr/lib64/pmdk_debug/libvmmalloc.so.1
/usr/lib64/pmdk_debug/libvmmalloc.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pmdk/3dbfb3fe97c5e5d656cd3ee22d970e7e73a7a6c6
/usr/share/package-licenses/pmdk/4b07e66cc7925c2a6e0c68d25b78f90c9be4fc68
/usr/share/package-licenses/pmdk/b37189216d7244b1bfd4a8c1e73085469c2ba9a6

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/daxio.1.gz
/usr/share/man/man1/pmempool-check.1.gz
/usr/share/man/man1/pmempool-convert.1.gz
/usr/share/man/man1/pmempool-create.1.gz
/usr/share/man/man1/pmempool-dump.1.gz
/usr/share/man/man1/pmempool-feature.1.gz
/usr/share/man/man1/pmempool-info.1.gz
/usr/share/man/man1/pmempool-rm.1.gz
/usr/share/man/man1/pmempool-sync.1.gz
/usr/share/man/man1/pmempool-transform.1.gz
/usr/share/man/man1/pmempool.1.gz
/usr/share/man/man1/pmreorder.1.gz
/usr/share/man/man5/pmem_ctl.5.gz
/usr/share/man/man5/poolset.5.gz
/usr/share/man/man7/libpmem.7.gz
/usr/share/man/man7/libpmemblk.7.gz
/usr/share/man/man7/libpmemlog.7.gz
/usr/share/man/man7/libpmemobj.7.gz
/usr/share/man/man7/libpmempool.7.gz
/usr/share/man/man7/libvmem.7.gz
/usr/share/man/man7/libvmmalloc.7.gz
